name: rck_abm
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cycler=0.10.0
  - decorator=4.4.2
  - freetype=2.10.4
  - intel-openmp=2021.2.0
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jpeg=9b
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=10.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - ncurses=6.2
  - networkx=2.5.1
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - pandas=1.2.4
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.1
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - pygments=2.9.0
  - pyparsing=2.4.7
  - python=3.7.10
  - python-dateutil=2.8.1
  - pytz=2021.1
  - readline=8.1
  - scipy=1.6.2
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
